[tool.poetry]
name = "polywrap-manifest"
version = "0.1.0"
description = "Polywrap Manifest Python Typings"
authors = ["Cesar <cesar@polywrap.io>"]
readme = "README.md"

[tool.poetry.dependencies]
chevron = "^0.14.0"
python = "^3.10"
statham = "^0.12"
json-ref-dict = "^0.7.1"
statham-schema = "^0.13.5"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-cov = "^3.0.0"

[tool.poetry.scripts]
generate = "polywrap_manifest.scripts.generate_manifest_types:generate"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
