version: 1.0.{build}
image: Visual Studio 2019

matrix:
  fast_finish: true  

cache:
  - C:\ProgramData\chocolatey\bin -> .nvmrc
  - C:\ProgramData\chocolatey\lib -> .nvmrc
  - ..\\.yarn-cache -> yarn.lock

install:
  - ps: "choco install nodejs-lts --version=$($(Get-Content .nvmrc).replace('v',''))"
  - npm i -g yarn
  - node --version
  - yarn --version

build_script:
  - yarn install --nonInteractive --frozen-lockfile --cache-folder ..\\.yarn-cache
  - yarn build

test_script:
  - docker version
  - docker-compose version
  - ps: "& 'C:/Program Files/Docker/Docker/DockerCli.exe' -SwitchDaemon -SwitchLinuxEngine"
  - yarn test:ci