[package]
name = "client-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "client_rs"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
wasmtime = "1.0.1"
serde = "1.0.145"
thiserror = "1.0.37"
rmp-serde = "1.1.1"
tokio = { version = "1", features = ["full"] }