format: 0.0.1-prealpha.2
repository: https://github.com
language: wasm/assemblyscript
build: ./web3api.build.wrong-config.yaml
modules:
  mutation:
    schema: ./src/mutation/schema.graphql
    module: ./src/mutation/index.ts
  query:
    schema: ./src/query/schema.graphql
    module: ./src/query/index.ts
