format: "0.3.0"
jobs:
  test:
    config:
      gatewayUri: $IPFS_GATEWAY_URI
    steps:
      - name: ipfs_deploy
        package: ipfs
        uri: fs/../wrapper
      - name: from_deploy
        package: ens
        uri: $$ipfs_deploy
        config:
          domainName: $NON_LOADED_VAR
          provider: 'http://localhost:8545'
          ensRegistryAddress: '0x9b1f7F645351AF3631a656421eD2e40f2802E6c0'
