format: "0.3.0"
jobs:
  test:
    config:
      gatewayUri: $IPFS_GATEWAY_URI
    steps:
      - name: ipfs_deploy
        package: ipfs
        uri: wrap://fs/./build
      - name: from_deploy
        package: ens
        uri: $$ipfs_deploy
        config:
          domainName: true
          ports:
            ethereum: 8545